site_name: DockDogs Scheduling
pages:
- Home: index.md
- Basics:
    - Basics and Introduction: getting-started/basics-and-introduction.md 
    - Status Icon Legend: getting-started/status-icon-legend.md
    - FAQS: getting-started/FAQs.md
- Reporting:
    - Reporting Basics: reporting/reporting-basics.md 
    - Creating A New Report: reporting/creating-a-new-report.md
    - Pre-Built Sponsors Report: reporting/pre-built-sponsors-report.md 
- Notifications:
    - Pre-Built Notifications: notifications/pre-build-notifications.md
    - Notification Basics: notifications/notifications-basics.md
theme: readthedocs

